export const GET_SINGLE_USERS_BEGIN = 'GET_PRODUCTS_BEGIN'
export const GET_SINGLE_USERS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_SINGLE_USERS_ERROR = 'GET_PRODUCTS_ERROR'
export const LOAD_USERS = 'LOAD_USERS'